<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Lee Bennett">

<title>ST 558 Homework 5: Exploratory Data Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ST 558 Homework 5: Exploratory Data Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Lee Bennett </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<p>In this homework assignment, we’ll use data from two Portuguese secondary schools from the UCI machine learninng repository to perform some exploratory data analysis. First, we’ll read in the datasets for math and Portuguese scores and then merge the datasets in two different ways. Next, we’ll explore the data by computing some summaries for both categorical and numeric variables.</p>
<section id="reading-and-modifying-the-data" class="level1">
<h1>Reading and Modifying the Data</h1>
<p>We’ll first read in and merge the data using the base R code provided on the UCI website.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>d1<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"student-mat.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>d2<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"student-por.csv"</span>,<span class="at">sep=</span><span class="st">";"</span>,<span class="at">header=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>d3<span class="ot">=</span><span class="fu">merge</span>(d1,d2,<span class="at">by=</span><span class="fu">c</span>(<span class="st">"school"</span>,<span class="st">"sex"</span>,<span class="st">"age"</span>,<span class="st">"address"</span>,<span class="st">"famsize"</span>,<span class="st">"Pstatus"</span>,<span class="st">"Medu"</span>,<span class="st">"Fedu"</span>,<span class="st">"Mjob"</span>,<span class="st">"Fjob"</span>,<span class="st">"reason"</span>,<span class="st">"nursery"</span>,<span class="st">"internet"</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">nrow</span>(d3)) <span class="co"># 382 students</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 382</code></pre>
</div>
</div>
<p>Next, let’s read in the data using the <code>tidyverse</code> function <code>read_delim</code> and merge the two sets of data using an inner join on the same variables specified above:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"student-mat.csv"</span>, <span class="at">delim=</span><span class="st">";"</span>, <span class="at">col_names=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 395 Columns: 33
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (17): school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardi...
dbl (16): age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data2 <span class="ot">&lt;-</span> <span class="fu">read_delim</span>(<span class="st">"student-por.csv"</span>, <span class="at">delim=</span><span class="st">";"</span>, <span class="at">col_names=</span><span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 649 Columns: 33
── Column specification ────────────────────────────────────────────────────────
Delimiter: ";"
chr (17): school, sex, address, famsize, Pstatus, Mjob, Fjob, reason, guardi...
dbl (16): age, Medu, Fedu, traveltime, studytime, failures, famrel, freetime...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>data_all <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(data1, data2, <span class="at">by=</span><span class="fu">c</span>(<span class="st">"school"</span>,<span class="st">"sex"</span>,<span class="st">"age"</span>,<span class="st">"address"</span>,<span class="st">"famsize"</span>,<span class="st">"Pstatus"</span>,<span class="st">"Medu"</span>,<span class="st">"Fedu"</span>,<span class="st">"Mjob"</span>,<span class="st">"Fjob"</span>,<span class="st">"reason"</span>,<span class="st">"nursery"</span>,<span class="st">"internet"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in inner_join(data1, data2, by = c("school", "sex", "age", "address", : Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 79 of `x` matches multiple rows in `y`.
ℹ Row 79 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.</code></pre>
</div>
</div>
<p>The results show that there is a many-to-many relationship when we attempt to join on all of the variables. To alleviate this problem, we’ll perform an inner join using all variables that the datasets have in common except for the variables <code>G1</code>, <code>G2</code>, <code>G3</code>, <code>paid</code>, and <code>absences</code>. This new combined dataset will be used for subsequent analyses.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Get the names of all variables that the two datasets have in common and remove the selected variables from the vector of names</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>all_vars<span class="ot">&lt;-</span><span class="fu">intersect</span>(<span class="fu">names</span>(data1),<span class="fu">names</span>(data2))</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>remove_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"G1"</span>, <span class="st">"G2"</span>, <span class="st">"G3"</span>, <span class="st">"paid"</span>, <span class="st">"absences"</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>remain_vars <span class="ot">&lt;-</span> all_vars[<span class="sc">!</span>all_vars <span class="sc">%in%</span> remove_vars]</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Join the datasets on the remaining common variables</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>ad_combined <span class="ot">&lt;-</span> <span class="fu">inner_join</span>(data1, data2, <span class="at">by=</span>remain_vars)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>ad_combined</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 320 × 38
   school sex     age address famsize Pstatus  Medu  Fedu Mjob     Fjob   reason
   &lt;chr&gt;  &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt; 
 1 GP     F        18 U       GT3     A           4     4 at_home  teach… course
 2 GP     F        17 U       GT3     T           1     1 at_home  other  course
 3 GP     F        15 U       GT3     T           4     2 health   servi… home  
 4 GP     F        16 U       GT3     T           3     3 other    other  home  
 5 GP     M        16 U       LE3     T           4     3 services other  reput…
 6 GP     M        16 U       LE3     T           2     2 other    other  home  
 7 GP     F        17 U       GT3     A           4     4 other    teach… home  
 8 GP     M        15 U       LE3     A           3     2 services other  home  
 9 GP     M        15 U       GT3     T           3     4 other    other  home  
10 GP     F        15 U       GT3     T           4     4 teacher  health reput…
# ℹ 310 more rows
# ℹ 27 more variables: guardian &lt;chr&gt;, traveltime &lt;dbl&gt;, studytime &lt;dbl&gt;,
#   failures &lt;dbl&gt;, schoolsup &lt;chr&gt;, famsup &lt;chr&gt;, paid.x &lt;chr&gt;,
#   activities &lt;chr&gt;, nursery &lt;chr&gt;, higher &lt;chr&gt;, internet &lt;chr&gt;,
#   romantic &lt;chr&gt;, famrel &lt;dbl&gt;, freetime &lt;dbl&gt;, goout &lt;dbl&gt;, Dalc &lt;dbl&gt;,
#   Walc &lt;dbl&gt;, health &lt;dbl&gt;, absences.x &lt;dbl&gt;, G1.x &lt;dbl&gt;, G2.x &lt;dbl&gt;,
#   G3.x &lt;dbl&gt;, paid.y &lt;chr&gt;, absences.y &lt;dbl&gt;, G1.y &lt;dbl&gt;, G2.y &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Finally, let’s convert four variables of interest into <code>factor</code> variables that we’ll summarize later. We’ll use the variables for mother’s and father’s educational attainment, weekly study time, and receipt of extra educational support:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>edu_labels <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"None"</span>,<span class="st">"Primary education"</span>,<span class="st">"5th to 9th grade"</span>,<span class="st">"Secondary education"</span>,<span class="st">"Higher education"</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>ad_data1 <span class="ot">&lt;-</span> data1 <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">MeduF=</span><span class="fu">factor</span>(Medu, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span>edu_labels),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">FeduF=</span><span class="fu">factor</span>(Fedu, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span>edu_labels),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">studytimeF=</span><span class="fu">factor</span>(studytime, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"&lt;2 hours"</span>,<span class="st">"2 to 5 hours"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>                                                                               <span class="st">"5 to 10 hours"</span>, <span class="st">"&gt;10 hours"</span>)),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">schoolsupF=</span><span class="fu">factor</span>(schoolsup,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"yes"</span>,<span class="st">"no"</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Extra support"</span>,<span class="st">"No extra support"</span>)))</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>                         </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>ad_data2 <span class="ot">&lt;-</span> data1 <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">MeduF=</span><span class="fu">factor</span>(Medu, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span>edu_labels),</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>                         <span class="at">FeduF=</span><span class="fu">factor</span>(Fedu, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span>edu_labels),</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>                         <span class="at">studytimeF=</span><span class="fu">factor</span>(studytime, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"&lt;2 hours"</span>,<span class="st">"2 to 5 hours"</span>,</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>                                                                               <span class="st">"5 to 10 hours"</span>, <span class="st">"&gt;10 hours"</span>)),</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>                         <span class="at">schoolsupF=</span><span class="fu">factor</span>(schoolsup,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"yes"</span>,<span class="st">"no"</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Extra support"</span>,<span class="st">"No extra support"</span>)))</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>ad_combined <span class="ot">&lt;-</span> ad_combined <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">MeduF=</span><span class="fu">factor</span>(Medu, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span>edu_labels),</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>                         <span class="at">FeduF=</span><span class="fu">factor</span>(Fedu, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span>edu_labels),</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>                         <span class="at">studytimeF=</span><span class="fu">factor</span>(studytime, <span class="at">levels=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>), <span class="at">labels=</span><span class="fu">c</span>(<span class="st">"&lt;2 hours"</span>,<span class="st">"2 to 5 hours"</span>,</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>                                                                               <span class="st">"5 to 10 hours"</span>, <span class="st">"&gt;10 hours"</span>)),</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>                         <span class="at">schoolsupF=</span><span class="fu">factor</span>(schoolsup,<span class="at">levels=</span><span class="fu">c</span>(<span class="st">"yes"</span>,<span class="st">"no"</span>),<span class="at">labels=</span><span class="fu">c</span>(<span class="st">"Extra support"</span>,<span class="st">"No extra support"</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="exploratory-data-analysis" class="level1">
<h1>Exploratory Data Analysis</h1>
<p>All of the analyses below were conducted using the combined dataset <code>ad_combined</code>. First, we’ll check the tibble to make sure that the variables appear to have the correct types and to see how much missing data there is for each variable:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(ad_combined))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    school        sex        age    address    famsize    Pstatus       Medu 
         0          0          0          0          0          0          0 
      Fedu       Mjob       Fjob     reason   guardian traveltime  studytime 
         0          0          0          0          0          0          0 
  failures  schoolsup     famsup     paid.x activities    nursery     higher 
         0          0          0          0          0          0          0 
  internet   romantic     famrel   freetime      goout       Dalc       Walc 
         0          0          0          0          0          0          0 
    health absences.x       G1.x       G2.x       G3.x     paid.y absences.y 
         0          0          0          0          0          0          0 
      G1.y       G2.y       G3.y      MeduF      FeduF studytimeF schoolsupF 
         0          0          0          0          0          0          0 </code></pre>
</div>
</div>
<p>The printout of the <code>ad_combined</code> tibble in the last section and the summary performed in the code immediately above indicate that all of the columns appears to have the correct type and there is no missing data.</p>
<section id="analysis-of-categorical-variables" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-categorical-variables">Analysis of Categorical Variables</h2>
<p>We’ll start the exploratory analysis by creating a series of contingency tables, beginning with a one-way table for extra support:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>tab1 <span class="ot">&lt;-</span> <span class="fu">table</span>(ad_combined<span class="sc">$</span>schoolsupF)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>tab1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   Extra support No extra support 
              43              277 </code></pre>
</div>
</div>
<p>We see that most students (277 out of 320) do not receive extra support. Let’s now look at how study time varies between those who receive support and those who don’t:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tab2 <span class="ot">&lt;-</span> <span class="fu">table</span>(ad_combined<span class="sc">$</span>schoolsupF,ad_combined<span class="sc">$</span>studytimeF)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tab2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  
                   &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Extra support          10           24             5         4
  No extra support       71          133            51        22</code></pre>
</div>
</div>
<p>Overall, study time doesn’t appear to vary much based on extra support status. The most frequent category of study time is 2 to 5 hours in both groups (24 out of 43 in the extra support group and 133 out of 277 in the no extra support group).</p>
<p>Next, let’s check to see if there is any evidence of maternal education level having an effect on the distribution of these study times by support status:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>tab3 <span class="ot">&lt;-</span> <span class="fu">table</span>(ad_combined<span class="sc">$</span>schoolsupF,ad_combined<span class="sc">$</span>studytimeF,ad_combined<span class="sc">$</span>FeduF)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>tab3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>, ,  = None

                  
                   &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Extra support           0            0             0         0
  No extra support        0            1             0         1

, ,  = Primary education

                  
                   &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Extra support           2            3             0         1
  No extra support       19           20             8         4

, ,  = 5th to 9th grade

                  
                   &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Extra support           2            8             0         1
  No extra support       16           37            15        10

, ,  = Secondary education

                  
                   &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Extra support           2            7             3         2
  No extra support       15           38            12         5

, ,  = Higher education

                  
                   &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Extra support           4            6             2         0
  No extra support       21           37            16         2</code></pre>
</div>
</div>
<p>We’ll next look at a conditional distribution of support status given that for students whose mothers received higher education, first using data filtering:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>tab_filtered <span class="ot">&lt;-</span> ad_combined <span class="sc">|&gt;</span> <span class="fu">filter</span>(FeduF<span class="sc">==</span><span class="st">"Higher education"</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(tab_filtered<span class="sc">$</span>schoolsupF,tab_filtered<span class="sc">$</span>studytimeF)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  
                   &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Extra support           4            6             2         0
  No extra support       21           37            16         2</code></pre>
</div>
</div>
<p>and next by subsetting the 3-way table created above:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>tab3[, ,<span class="st">"Higher education"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  
                   &lt;2 hours 2 to 5 hours 5 to 10 hours &gt;10 hours
  Extra support           4            6             2         0
  No extra support       21           37            16         2</code></pre>
</div>
</div>
<p>Now let’s use the <code>tidyverse</code> to create a two-way contingency table of study time by support status to see that we get the same result shown earlier:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>ad_combined <span class="sc">|&gt;</span> <span class="fu">group_by</span>(schoolsupF,studytimeF) <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="at">count=</span><span class="fu">n</span>()) <span class="sc">|&gt;</span> <span class="fu">pivot_wider</span>(<span class="at">names_from=</span>studytimeF,<span class="at">values_from=</span>count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'schoolsupF'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
# Groups:   schoolsupF [2]
  schoolsupF       `&lt;2 hours` `2 to 5 hours` `5 to 10 hours` `&gt;10 hours`
  &lt;fct&gt;                 &lt;int&gt;          &lt;int&gt;           &lt;int&gt;       &lt;int&gt;
1 Extra support            10             24               5           4
2 No extra support         71            133              51          22</code></pre>
</div>
</div>
<p>Finally, let’s create a couple of graphs. First, a stacked bar chart showing the distribution of study times by maternal education level:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>stacked_bar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> ad_combined, <span class="fu">aes</span>(<span class="at">x =</span> MeduF, <span class="at">fill =</span> studytimeF)) <span class="sc">+</span> <span class="fu">geom_bar</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Maternal educational level"</span>, <span class="at">y =</span> <span class="st">"N"</span>, <span class="at">title=</span><span class="st">"Study time by maternal educational level"</span>) <span class="sc">+</span> <span class="fu">scale_fill_discrete</span>(<span class="st">"Study Time"</span>) <span class="sc">+</span> <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">n.dodge=</span><span class="dv">2</span>)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>stacked_bar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Next, we’ll plot the same two variables in a side-by-side bar graph:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>side_bar <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> ad_combined, <span class="fu">aes</span>(<span class="at">x =</span> MeduF, <span class="at">fill =</span> studytimeF)) <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Maternal educational level"</span>, <span class="at">y =</span> <span class="st">"N"</span>, <span class="at">title=</span><span class="st">"Study time by maternal educational level"</span>) <span class="sc">+</span> <span class="fu">scale_fill_discrete</span>(<span class="st">"Study Time"</span>) <span class="sc">+</span> <span class="fu">scale_x_discrete</span>(<span class="at">guide =</span> <span class="fu">guide_axis</span>(<span class="at">n.dodge=</span><span class="dv">2</span>)) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>side_bar</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see again that the most frequently observed maternal educational level is higher education, but both graphs show that the distributions of student study time within education levels are similar.</p>
</section>
<section id="analysis-of-numerical-variables" class="level2">
<h2 class="anchored" data-anchor-id="analysis-of-numerical-variables">Analysis of Numerical Variables</h2>
<p>For the first summary, we’ll compute the mean, median, and range for age and the two final grade variables:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>ad_combined <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age,G3.x,G3.y),<span class="fu">list</span>(<span class="st">"mean"</span><span class="ot">=</span>mean,<span class="st">"median"</span><span class="ot">=</span>median,<span class="st">"sd"</span><span class="ot">=</span>sd),<span class="at">.names=</span><span class="st">"{.fn}_{.col}"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 9
  mean_age median_age sd_age mean_G3.x median_G3.x sd_G3.x mean_G3.y median_G3.y
     &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
1     16.5         16   1.14      11.0          11    4.30      12.9          13
# ℹ 1 more variable: sd_G3.y &lt;dbl&gt;</code></pre>
</div>
</div>
<p>We see that the median age is 16, and that the average final score in Portuguese (mean = 12.88) is higher than the final score in math (mean = 11.04). Let’s break it down further by computing these summary statistics according to support status:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>ad_combined <span class="sc">|&gt;</span> <span class="fu">group_by</span>(schoolsupF) <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age,G3.x,G3.y),<span class="fu">list</span>(<span class="st">"mean"</span><span class="ot">=</span>mean,<span class="st">"median"</span><span class="ot">=</span>median,<span class="st">"sd"</span><span class="ot">=</span>sd),<span class="at">.names=</span><span class="st">"{.fn}_{.col}"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 10
  schoolsupF  mean_age median_age sd_age mean_G3.x median_G3.x sd_G3.x mean_G3.y
  &lt;fct&gt;          &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;
1 Extra supp…     15.9         16  0.956      9.58          10    2.99      11.5
2 No extra s…     16.6         17  1.14      11.3           11    4.43      13.1
# ℹ 2 more variables: median_G3.y &lt;dbl&gt;, sd_G3.y &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Here, we notice that those who received extra support were younger, on average, than those who did not. The extra support group also had mean final grades which were lower than those with no extra support. Let’s now group by maternal education:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>ad_combined <span class="sc">|&gt;</span> <span class="fu">group_by</span>(schoolsupF,MeduF) <span class="sc">|&gt;</span> <span class="fu">summarize</span>(<span class="fu">across</span>(<span class="fu">c</span>(age,G3.x,G3.y),<span class="fu">list</span>(<span class="st">"mean"</span><span class="ot">=</span>mean,<span class="st">"median"</span><span class="ot">=</span>median,<span class="st">"sd"</span><span class="ot">=</span>sd),<span class="at">.names=</span><span class="st">"{.fn}_{.col}"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'schoolsupF'. You can override using the
`.groups` argument.</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 11
# Groups:   schoolsupF [2]
  schoolsupF      MeduF mean_age median_age sd_age mean_G3.x median_G3.x sd_G3.x
  &lt;fct&gt;           &lt;fct&gt;    &lt;dbl&gt;      &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;
1 Extra support   Prim…     16.2       16    1.26       9.75         9.5   0.957
2 Extra support   5th …     15.8       15.5  0.931     10.8         10.5   2.59 
3 Extra support   Seco…     15.5       15.5  0.527      9.5         11     2.46 
4 Extra support   High…     16.2       16    1.09       8.08         8     3.71 
5 No extra suppo… None      16.5       16.5  0.707     15           15     0    
6 No extra suppo… Prim…     16.9       17    1.13       9.55        10     3.99 
7 No extra suppo… 5th …     16.7       17    0.993     10.0         11     4.80 
8 No extra suppo… Seco…     16.8       17    1.21      11.2         11     4.50 
9 No extra suppo… High…     16.4       16    1.17      12.5         13     3.96 
# ℹ 3 more variables: mean_G3.y &lt;dbl&gt;, median_G3.y &lt;dbl&gt;, sd_G3.y &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Within the extra support group, the mean and median ages are notably lower for students whose mothers in the 5th to 9th grade and secondary education groups compared to all other groups.</p>
<p>To examine associations between the numeric variables, we can compute the linear (Pearson) correlation for each pair of the numeric variables as a matrix:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>ad_combined <span class="sc">|&gt;</span> <span class="fu">select</span>(age,absences.x,absences.y,G1.x,G1.y,G2.x,G2.y,G3.x,G3.y) <span class="sc">|&gt;</span> <span class="fu">cor</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    age  absences.x  absences.y        G1.x        G1.y
age         1.000000000  0.14392517  0.04733182 -0.11037935 -0.05054968
absences.x  0.143925170  1.00000000  0.56381559 -0.06946116 -0.09247761
absences.y  0.047331821  0.56381559  1.00000000 -0.08760610 -0.09864117
G1.x       -0.110379348 -0.06946116 -0.08760610  1.00000000  0.59293522
G1.y       -0.050549678 -0.09247761 -0.09864117  0.59293522  1.00000000
G2.x       -0.186187399 -0.07580245 -0.12636236  0.86588796  0.54300736
G2.y        0.029366456 -0.14516402 -0.12070727  0.59517224  0.88415041
G3.x       -0.206031862 -0.02811847 -0.11664046  0.81859418  0.52288461
G3.y       -0.009103257 -0.13572638 -0.07145201  0.54388734  0.82541432
                  G2.x        G2.y        G3.x         G3.y
age        -0.18618740  0.02936646 -0.20603186 -0.009103257
absences.x -0.07580245 -0.14516402 -0.02811847 -0.135726385
absences.y -0.12636236 -0.12070727 -0.11664046 -0.071452010
G1.x        0.86588796  0.59517224  0.81859418  0.543887345
G1.y        0.54300736  0.88415041  0.52288461  0.825414320
G2.x        1.00000000  0.56521350  0.91357599  0.496032649
G2.y        0.56521350  1.00000000  0.54545279  0.894309821
G3.x        0.91357599  0.54545279  1.00000000  0.475956497
G3.y        0.49603265  0.89430982  0.47595650  1.000000000</code></pre>
</div>
</div>
<p>We notice here that each individual period score is highly correlated with the final score, within subject: for example, the correlation for the first period math grade and the final math grade is 0.818.</p>
<p>To explore some of the numerical data graphically, we’ll first create a histogram of the final math grades by support status:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>hist_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ad_combined, <span class="fu">aes</span>(<span class="at">x=</span>G3.x, <span class="at">fill=</span>schoolsupF)) <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="at">binwidth=</span><span class="dv">2</span>,<span class="at">alpha=</span><span class="fl">0.4</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.4</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Final math grade"</span>, <span class="at">y=</span><span class="st">"N"</span>, <span class="at">title=</span><span class="st">"Final math grade by support received"</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="st">"Support"</span>,<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Extra support"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"No extra support"</span> <span class="ot">=</span> <span class="st">"green"</span>))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>                                                                                  </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>hist_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This histogram suggests that students who received extra support tended to be less likely to receive higher final grades, but it’s not clear. We can create a kernel density plot of the same information:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>kernel_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ad_combined, <span class="fu">aes</span>(<span class="at">x=</span>G3.x, <span class="at">fill=</span>schoolsupF)) <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="at">alpha=</span><span class="fl">0.5</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Final math grade"</span>, <span class="at">y=</span><span class="st">"N"</span>, <span class="at">title=</span><span class="st">"Final math grade by support received"</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="st">"Support"</span>,<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Extra support"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"No extra support"</span> <span class="ot">=</span> <span class="st">"green"</span>))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>kernel_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot more clearly shows that students who received extra support were less likely to receive final math grades on the higher end of the scale. Let’s create a boxplot to visually check the mean and variation for the final math grades:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>box_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ad_combined, <span class="fu">aes</span>(<span class="at">x=</span>schoolsupF, <span class="at">y=</span>G3.x, <span class="at">fill=</span>schoolsupF)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Support status"</span>, <span class="at">y=</span><span class="st">"Final math grade"</span>, <span class="at">title=</span><span class="st">"Final math grade by support received"</span>) <span class="sc">+</span> <span class="fu">scale_fill_manual</span>(<span class="st">"Support"</span>,<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Extra support"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"No extra support"</span> <span class="ot">=</span> <span class="st">"green"</span>))</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>box_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that students who received extra support had a median final grade that was only slightly lower than those didn’t receive extra support, but that more members of extra support group had grades toward the lower end of the scale.</p>
<p>Finally, we’ll examine a few scatterplots related to the final math grade:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>scatter_1<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ad_combined, <span class="fu">aes</span>(<span class="at">x =</span> absences.x, <span class="at">y =</span> G3.x, <span class="at">color =</span> schoolsupF)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Absences"</span>, <span class="at">y=</span><span class="st">"Final math grade"</span>, <span class="at">title=</span><span class="st">"Final math grade vs. number of absences"</span>, <span class="at">subtitle=</span><span class="st">"By support status"</span>, <span class="at">color=</span><span class="st">"Support status"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>),<span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>scatter_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are no clearly discernable differences between the support status groups, but we do see that all of the students who finished with a zero grade also had no absences.</p>
<p>Now let’s compare the final math grade to the grade received during the first period:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>scatter_1<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ad_combined, <span class="fu">aes</span>(<span class="at">x =</span> G1.x, <span class="at">y =</span> G3.x, <span class="at">color =</span> schoolsupF)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"First period math grade"</span>, <span class="at">y=</span><span class="st">"Final math grade"</span>, <span class="at">title=</span><span class="st">"Final math grade vs. first period math grade"</span>, <span class="at">subtitle=</span><span class="st">"By support status"</span>, <span class="at">color=</span><span class="st">"Support status"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="at">plot.subtitle=</span><span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>scatter_1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>As we saw in the correlation matrix, there is a positive association between the grade received in the first period and the final math grade overall, and plot shows that the association holds for students who received extra support and those who didn’t. An interesting point here is that several students who did not receive support received a final grade of zero despite having first period grades ranging from 6 to 8, compared to only 1 student who received extra support.</p>
<p>We can use faceting to get the same kind of scatterplots for each level of study time:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>scatter_2<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ad_combined, <span class="fu">aes</span>(<span class="at">x =</span> G1.x, <span class="at">y =</span> G3.x, <span class="at">color =</span> schoolsupF)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"First period math grade"</span>, <span class="at">y=</span><span class="st">"Final math grade"</span>, <span class="at">title=</span><span class="st">"Final math grade vs. first period math grade"</span>, <span class="at">subtitle=</span><span class="st">"By support status and study time"</span>, <span class="at">color=</span><span class="st">"Support status"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="at">plot.subtitle=</span><span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">facet_wrap</span>(<span class="sc">~</span>studytimeF)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>scatter_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>These plots reveal that the positive relationship holds across each level of study time. We also see that the one student with extra support whom we noted earlier had received final grade of zero despite a first period grade of between 6 and 8 averaged more than 10 hours of study time.</p>
<p>Finally, we’ll facet by another categorical variable (father’s education) to get a grid of scatterplots, one for each level of educational attainment:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>scatter_3<span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ad_combined, <span class="fu">aes</span>(<span class="at">x =</span> G1.x, <span class="at">y =</span> G3.x, <span class="at">color =</span> schoolsupF)) <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="at">position=</span><span class="st">"jitter"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"First period math grade"</span>, <span class="at">y=</span><span class="st">"Final math grade"</span>, <span class="at">title=</span><span class="st">"Final math grade vs. first period math grade"</span>, <span class="at">subtitle=</span><span class="st">"By support status, study time, and paternal education"</span>, <span class="at">color=</span><span class="st">"Support status"</span>) <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>), <span class="at">plot.subtitle=</span><span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>)) <span class="sc">+</span> <span class="fu">facet_grid</span>(FeduF <span class="sc">~</span> schoolsupF)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>scatter_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="ST558_HW5_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>